apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: matiasroje/cast-service-dev:1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://cast_db_username:cast_db_password@cast-db:5433/cast_db_dev
---
apiVersion: v1
kind: Service
metadata:
  name: cast-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: cast-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8000