apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust storage size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine

        env:
        - name: POSTGRES_USER
          value: movie_db_username
        - name: POSTGRES_PASSWORD
          value: movie_db_password
        - name: POSTGRES_DB
          value: movie_db_dev

        volumeMounts:
        - name: movie-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: movie-db-data
        persistentVolumeClaim:
          claimName: movie-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  namespace: prod
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: 5432  # Default Postgres port
      targetPort: 5432