apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: matiasroje/movie-service:24
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: prod
spec:
  type: ClusterIP  # Using ClusterIP for internal communication
  selector:
    app: movie-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8000